### PR TITLE
feat: create libraries page to comply with lgpl

### PR DESCRIPTION
**Pull request by Gravy59**
Create a list of libraries (if more are used under lgpl).
Add the page to the navbar (may or may not be more compliant).
There may be a potential issue regarding tabs/spaces.

### CODE REVIEW

**Comment by JJL772** [comment]
Looks good, I can take a closer look at this soon. If it's good, I think I'll merge it into a separate branch until we actually ship hammer Qt.

Additionally, we need to host a zip of the modified Qt6 source code on the site.

**Comment by Gravy59** [comment]
Yes, I just discovered a bug that I overlooked - I forgot to put a hashtag for the download link. Easily fixable.

**Comment by Gravy59** [comment]
This is done better in PR #12 unless you have multiple libraries under LGPL. However, #12 can fix that as well.

**Comment by JJL772** [comment]
I appreciate the effort nonetheless

**Pull request closed without merging**
